spring.application.name=estacionaAI
spring.datasource.url=jdbc:mysql://localhost:3306/estaciona_qa?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
spring.banner.location=classpath:banner-qa.txt